baseURL       = "http://example.org/"
languageCode  = "en-us"
title         = "My New Hugo Site"
theme         = "my_gohugo-theme"
themesDir     = "./themes"

[params]
  title       = "Mairie de Strasbourg"
  subtitle    = "My Hugo Site"

  cover       = "img/jumbotron.jpg"
  description = "Here is a description of your site."

  logo        = "img/hugo-logo.png"
  navbarLogo  = "img/favicon.ico"

  themeColor  = "light"

  addressStreet = "4 rue du Dôme"
  addressCity   = "67000 Strasbourg"
  telNumber     = "0677889922"

  mail = "manuel.konrath@gmail.com"


[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200


[[menu.main]]
  name = "Associations"
  url = "/associations"
  weight = 100


[[menu.main]]
  name = "Municipal Council"
  identifier = "council"
  url = "/municipal_council"
  weight = 99


[[menu.main]]
  name = "Events"
  identifier = "events"
  weight = 95

  [[menu.main]]
    name = "All Events"
    parent = "events"
    url = "/events"
    weight = 50

  [[menu.main]]
    name = "Upcoming Events"
    parent = "events"
    url = "/events/upcoming_events"
    weight = 50

  [[menu.main]]
    name = "Archived Events"
    parent = "events"
    url = "/archived-Events"
    weight = 45

  [[menu.main]]
    name = "Calendar"
    parent = "events"
    url = "/calendar"
    weight = 30
